name = "persevero"
version = "1.1.0"

description = "Execute fallible operations multiple times."
licences = ["Apache-2.0"]
repository = { type = "github", user = "JosephTLyons", repo = "persevero" }

[dependencies]
bigben = ">= 1.0.0 and < 2.0.0"
birl = ">= 1.7.1 and < 2.0.0"
gleam_erlang = ">= 0.30.0 and < 1.0.0"
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_yielder = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
